services:
  api:
    image: ghcr.io/ministryofjustice/hmpps-assess-risks-and-needs:local
    build:
      target: development
    command: gradle --parallel --build-cache --configuration-cache bootRun
    volumes:
      - ./.git:/app/.git
      - ./.gradle:/home/gradle/.gradle
      - ./build:/app/build
      - ./src:/app/src
      - ./build.gradle.kts:/app/build.gradle.kts
      - ./settings.gradle.kts:/app/settings.gradle.kts
    ports:
      - "8080:8080"
      - "5005:5005"
