---
# Per environment values which override defaults in hmpps-assess-risks-and-needs/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: assess-risks-and-needs.hmpps.service.justice.gov.uk
    contextColour: green
    annotations:
      external-dns.alpha.kubernetes.io/aws-weight: "100"

  env:
    OAUTH_ENDPOINT_URL: https://sign-in.hmpps.service.justice.gov.uk/auth
    COMMUNITY_API_BASE_URL: https://arns-and-delius.hmpps.service.justice.gov.uk
    OASYS_API_BASE_URL: https://oasys.service.justice.gov.uk/eor/oasys
    SPRING_PROFILES_ACTIVE: "logstash,postgres,oasys-rsr"
generic-prometheus-alerts:
  enabled: true
  alertSeverity: hmpps-assess-risks-and-needs

dataExtractor:
  enabled: true

is_production: true
