name: Integration Test

on:
  workflow_call:
    inputs:
      environment:
        description: Environment
        type: string
        required: true
        default: 'dev'

permissions:
  contents: read

jobs:
  inttest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Int Tests
        run: make int-test-${{ inputs.environment }}

      - name: Upload test results
        if: '!cancelled()'
        uses: actions/upload-artifact@v5
        with:
          name: test_results
          path: |
            build/test_results
            build/reports/tests
      
      - name: Slack notification
        if: failure()
        uses: slackapi/slack-github-action@v3.0.3
        env:
          SLACK_CHANNEL: ${{ vars.INTEGRATION_ALERTS_SLACK_CHANNEL_ID || 'NO_SLACK' }}
          REPO_NAME: ${{ github.repository }}
          SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SLACK_BOT_TOKEN }}
        with:
          method: chat.postMessage
          token: ${{ secrets.HMPPS_SLACK_BOT_TOKEN }}
          payload: |
            {
              "channel": "${{ env.SLACK_CHANNEL }}",
              "text": "🚨 ${{ inputs.environment }} - API Smoke Tests Failed",
              "attachments": [
               {
                 "color": "#FF0000",
                 "text": ":x: *API Smoke tests notification*\nWorkflow failed on ${{ inputs.environment }} environment for ${{ env.REPO_NAME }}"
                }
              ]
            }
