name: Trigger E2E Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: Environment
        type: string
        required: true
        default: 'dev'
  workflow_call:
    inputs:
      environment:
        description: Environment
        type: string
        required: true
        default: 'dev'

permissions:
  contents: read
  packages: write
  id-token: write

jobs:
  checkout_e2e_tests:
    name: Trigger e2e tests
    if: contains(fromJSON('["dev", "test"]'), inputs.environment)
    runs-on: [ self-hosted, hmpps-github-actions-runner ]
    outputs:
      token: ${{ steps.octo_sts.outputs.token }}
    steps:
      - name: Obtain Octo STS Token
        uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05
        id: octo_sts
        with:
          scope: ministryofjustice/hmpps-arns-integrations-test-playwright
          identity: moj-hmpps-assess-risks-and-needs
      # - name: Checkout arns e2e tests
      #   id: checkout_e2e_repo
      #   uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
      #   with:
      #     persist-credentials: false
      #     token: ${{ steps.octo_sts.outputs.token }}
      #     repository: ministryofjustice/hmpps-arns-integrations-test-playwright
      #     path: e2e-tests

  run_e2e_tests:
    name: Run e2e tests
    needs: checkout_e2e_tests
    uses: ministryofjustice/hmpps-arns-integrations-test-playwright/.github/workflows/playwright-e2e.yml@ci-playwright-e2e
    with:
      environment: ${{ inputs.environment }}
      source: arns
    secrets:
      token: ${{ needs.checkout_e2e_tests.outputs.token }}
